"""Professional demo data for screenshots and local previews."""
from __future__ import annotations

DEMO_SERVICES = [
    {
        "name": "Jellyfin",
        "url": "http://media.local:8096",
        "host": "media.local",
        "port": 8096,
        "category": "Media",
        "icon": "jellyfin",
        "pinned": True,
        "has_login": True,
        "protocol": "http",
        "is_online": True,
        "auto_discovered": True,
    },
    {
        "name": "Grafana",
        "url": "http://monitor.local:3000",
        "host": "monitor.local",
        "port": 3000,
        "category": "Monitoring",
        "icon": "grafana",
        "pinned": True,
        "has_login": False,
        "protocol": "http",
        "is_online": True,
        "auto_discovered": True,
    },
    {
        "name": "Plex",
        "url": "http://media.local:32400",
        "host": "media.local",
        "port": 32400,
        "category": "Media",
        "icon": "plex",
        "pinned": True,
        "has_login": True,
        "protocol": "http",
        "is_online": False,
        "auto_discovered": True,
    },
    {
        "name": "n8n",
        "url": "http://automation.local:5678",
        "host": "automation.local",
        "port": 5678,
        "category": "Automation",
        "icon": "n8n",
        "pinned": True,
        "has_login": True,
        "protocol": "http",
        "is_online": True,
        "auto_discovered": True,
    },
    {
        "name": "Portainer",
        "url": "http://docker.local:9000",
        "host": "docker.local",
        "port": 9000,
        "category": "Docker",
        "icon": "docker",
        "pinned": False,
        "has_login": True,
        "protocol": "http",
        "is_online": True,
        "auto_discovered": True,
    },
    {
        "name": "Home Assistant",
        "url": "http://smart.local:8123",
        "host": "smart.local",
        "port": 8123,
        "category": "Smart Home",
        "icon": "homeassistant",
        "pinned": False,
        "has_login": True,
        "protocol": "http",
        "is_online": True,
        "auto_discovered": True,
    },
    {
        "name": "Proxmox",
        "url": "https://hypervisor.local:8006",
        "host": "hypervisor.local",
        "port": 8006,
        "category": "Virtualization",
        "icon": "proxmox",
        "pinned": False,
        "has_login": True,
        "protocol": "https",
        "is_online": True,
        "auto_discovered": True,
    },
]

DEMO_KEYS = [
    {
        "name": "Grafana API",
        "secret": "glsa_demo_key_masked_value",
        "service": "Grafana",
        "username": "admin",
        "notes": "Read-only dashboard token",
        "pinned": True,
    },
    {
        "name": "Home Assistant",
        "secret": "eyJ_demo_token_value_here",
        "service": "HA",
        "notes": "Long-lived access token",
        "pinned": False,
    },
]

DEMO_NOTES = [
    {
        "title": "Router config",
        "content": "**Gateway:** 192.168.1.1\n- WiFi: WPA3\n- VLAN 10: IoT",
        "color": "blue",
        "pinned": True,
    },
    {
        "title": "Backup schedule",
        "content": "Daily at 03:00 — NAS + cloud sync",
        "color": "green",
        "pinned": False,
    },
]
