# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
# Watchtower bez profilu — dla Container Station (Import drugiego pliku lub merge w UI)
services:
  watchtower:
    profiles: []
